### ISSUE TITLE
Rich Picture

### ISSUE THREAD

**Issue by ErickGiffoni** [Requisitos-de-Software/2019.2-Twitter#1]
## Descrição
Cada integrante do grupo deve fazer um Rich Picture para o Twitter e postar o resultado nos comentários abaixo.

**Comment by fernand0aguilar** [comment]
![C59D8E03-6255-4C36-8333-7C9153843626](https://user-images.githubusercontent.com/16293264/64023695-42f7e100-cb0f-11e9-8791-f7a49e2d4f97.jpeg)

**Comment by ErickGiffoni** [comment]
Já fiz a minha rich picture para o Twitter 👍 


![twitter_rich_picture_1](https://user-images.githubusercontent.com/33759461/63970640-0c708680-ca7b-11e9-8539-3391c40d3f65.jpg)

**Comment by Mexazonic** [comment]
Minha visão da Ritch Picture do Twitter

![Alt Text](https://i.imgur.com/UuhI9vI.png)

**Comment by lorryaze** [comment]
![rich](https://user-images.githubusercontent.com/30262806/64068760-f4cc0600-cc12-11e9-91ed-dfb1930de86b.jpg)

**Comment by Eugeniosales** [comment]
![photo5141202331965171755](https://user-images.githubusercontent.com/42457772/64070035-12f32f80-cc2e-11e9-9d58-7b0cd69f0109.jpg)

**Comment by aline-lv** [comment]
![RichPicture-Aline](https://user-images.githubusercontent.com/16181794/64170708-24ebf280-ce27-11e9-81de-a55d492ba27f.jpg)
