### ISSUE TITLE
Melhorar o RichPicture

### ISSUE THREAD

**Issue by fernand0aguilar** [Requisitos-de-Software/2019.2-Twitter#10]
- [ ] Fazer versão atualizada 
- [ ] Digitalizar

**Comment by ErickGiffoni** [comment]
@Mexazonic já concluiu essa parte ?
Tem 2 checklists acima

**Comment by ErickGiffoni** [comment]
@Mexazonic

**Comment by Mexazonic** [comment]
Aguardando análise dos critérios em checklist para realização do Rich Picture na versão digitalizada.
