### ISSUE TITLE
Utilizar o Twitter à nosso favor

### ISSUE THREAD

**Issue by fernand0aguilar** [Requisitos-de-Software/2019.2-Twitter#9]
- Lançar threads com perguntas sobre o Twitter;
- Fazer um meta-questionario (questionario no twitter sobre o twitter)
- Documentar as respostas e os requisitos levantados;

**Comment by fernand0aguilar** [comment]
Temos que pensar em um questionario, no twitter tem como criar umas perguntas de seleção tipo poll e ver as estatisticas

**Comment by fernand0aguilar** [comment]
no contexto de rede social

**Comment by ErickGiffoni** [comment]
Qual é a ideia em fazer isso ?
